# Use official Python image
FROM python:3.11-slim

# Set working directory to root (.)
WORKDIR /

# Copy requirements first
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files (including main.py, STORAGE/, etc.)
COPY . .

# Expose FastAPI port
EXPOSE 8003

# Mark STORAGE as volume
VOLUME ["/STORAGE"]

# Run FastAPI app
CMD ["python3", "main.py"]
